### ISSUE TITLE
Implement Mixpanel tracking

### ISSUE THREAD

**Issue by avorio** [avorio/paraentender#18]
- [x] Implement Drupal module mixpanel
- [x] Implement Drupal module rules
- [x] Implement Drupal module entity
- [x] Configure Drupal module mixpanel
- [x] Create rules to track events: view-page, view-article & download
